# This is a basic workflow to help you get started with Actions

name: Deploy to AWS Lambda Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out TestLambda Project
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 5.3.x
        
      - name: Restore NuGet Packages
        run: nuget restore GitHubLambda.sln
        
      - name: Build Solution
        run: msbuild GitHubLambda.sln /p:Configuration=Release
        
      - name :  Zip Bin folder
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 build.7z ./build/
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: GitHubActions_Lambda
          zip_file: bundle.zip
